-- MySQL Script generated by MySQL Workbench
-- Tue Jul 26 23:00:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_donkeyCar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_donkeyCar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_donkeyCar` DEFAULT CHARACTER SET utf8 ;
USE `BD_donkeyCar` ;

-- -----------------------------------------------------
-- Table `BD_donkeyCar`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_donkeyCar`.`type` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `nameType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BD_donkeyCar`.`pageContent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_donkeyCar`.`vehicle` (
  `idvehicle` INT NOT NULL AUTO_INCREMENT,
  `brandVehicle` VARCHAR(45) NOT NULL,
  `modelsVehicle` VARCHAR(45) NOT NULL,
  `energyVehicle` VARCHAR(45) NOT NULL,
  `yearVehicle` DATE NOT NULL,
  `nbseatsVehicle` INT NOT NULL,
  `gearboxVehicle` VARCHAR(45) NOT NULL,
  `imgVehicle` VARCHAR(300) NOT NULL,
  `prixLocVehicle` INT NOT NULL,
  `type_idtype` INT NOT NULL,
  PRIMARY KEY (`idvehicle`),
  INDEX `fk_vehicle_type1_idx` (`type_idtype` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_type1`
    FOREIGN KEY (`type_idtype`)
    REFERENCES `BD_donkeyCar`.`type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BD_donkeyCar`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_donkeyCar`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BD_donkeyCar`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_donkeyCar`.`reservation` (
  `idreservation` INT NOT NULL AUTO_INCREMENT,
  `dateReservationDebut` DATE NOT NULL,
  `dateReservationFin` DATE NOT NULL,
  `insuranceReservation` VARCHAR(45) NULL,
  `adddriverReservation` VARCHAR(45) NULL,
  `babyseatReservation` VARCHAR(45) NULL,
  `gpsReservation` VARCHAR(45) NULL,
  `prixTotalReservation` VARCHAR(45) NOT NULL,
  `vehicle_idvehicle` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idreservation`),
  INDEX `fk_reservation_vehicle1_idx` (`vehicle_idvehicle` ASC) VISIBLE,
  INDEX `fk_reservation_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_vehicle1`
    FOREIGN KEY (`vehicle_idvehicle`)
    REFERENCES `BD_donkeyCar`.`vehicle` (`idvehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `BD_donkeyCar`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `BD_donkeyCar`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_donkeyCar`.`session` (
  `id` CHAR(64) NOT NULL,
  `userid` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
